#!/bin/bash

# sudo apt-get install libc6-dev-i386 lib32z1 default-jdk
(while sleep 3; do echo "y"; done) | sudo apt-get install libc6-dev-i386 lib32z1

curl -O https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
curl -O https://dl.google.com/android/repository/tools_r25.2.3-linux.zip
