#!/bin/bash

set_path_file="$HOME/.bash_profile"

echo -e "input your gradle install path:"
read gradleInstallPath
if [ -n "${gradleInstallPath}" ]; then
  echo -e "you set install gradle path is ${gradleInstallPath}"
else
  echo -e "you are not set gradle install path, exit"
  exit 1
fi

# check gradle install path
if [ ! -d "${gradleInstallPath}" ]; then
  echo -e "you gradle install path is empty, exit"
  exit 1
fi

echo -e "This script set event of gradle!
Env set file path: ${set_path_file}
gradle_HOME -> ${gradleInstallPath}
\n"

if [ ! -f "${set_path_file}" ]; then
  cat > "${set_path_file}" << EOF
# environment set by https://github.com/sinlov/Golang-Shell

EOF
fi

cat >> "${set_path_file}" << EOF

# set gradle environment
export gradle_HOME=${gradleInstallPath}
export PATH=\$gradle_HOME/bin:\$PATH
EOF
echo -e "gradle evn set at ${set_path_file}
You can change by your self vim ${set_path_file}
load path by source ${set_path_file}"

