#!/bin/bash

set_path_file="$HOME/.bash_profile"

echo -e "input your maven install path:"
read mavenInstallPath
if [ -n "${mavenInstallPath}" ]; then
  echo -e "you set install maven path is ${mavenInstallPath}"
else
  echo -e "you are not set maven install path, exit"
  exit 1
fi

# check maven install path
if [ ! -d "${mavenInstallPath}" ]; then
  echo -e "you maven install path is empty, exit"
  exit 1
fi

echo -e "This script set event of maven!
Env set file path: ${set_path_file}
MAVEN_HOME -> ${mavenInstallPath}
\n"

if [ ! -f "${set_path_file}" ]; then
  cat > "${set_path_file}" << EOF
# environment set by https://github.com/sinlov/Golang-Shell

EOF
fi

cat >> "${set_path_file}" << EOF

# set maven environment
export MAVEN_HOME=${mavenInstallPath}
export PATH=\$MAVEN_HOME/bin:\$PATH
EOF
echo -e "maven evn set at ${set_path_file}
You can change by your self vim ${set_path_file}
load path by source ${set_path_file}"

